import { useEffect, useState } from "react";
import Head from "next/head";

import { useSupabaseClient } from "@supabase/auth-helpers-react";

import { Button } from "primereact/button";

import Layout from "../src/shared/components/layout";

export default function Home() {
  const supabase = useSupabaseClient();
  const [menu, setMenu] = useState<any>([]);

  const initialize = async () => {
    const { data, error } = await supabase.from("menu").select("*");
    setMenu(data);
  };
  useEffect(() => {
    initialize();
  }, []);
  return (
    <>
      <Layout mode="lessAuth">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {menu.map((m: any) => (
          <div key={m.id}>
            <h1>{m.name}</h1>
          </div>
        ))}
      </Layout>
    </>
  );
}
